/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatabaseDatabaseIdRouteImport } from './routes/database.$databaseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseDatabaseIdRoute = DatabaseDatabaseIdRouteImport.update({
  id: '/database/$databaseId',
  path: '/database/$databaseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/database/$databaseId': typeof DatabaseDatabaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/database/$databaseId': typeof DatabaseDatabaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/database/$databaseId': typeof DatabaseDatabaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/database/$databaseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/database/$databaseId'
  id: '__root__' | '/' | '/database/$databaseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatabaseDatabaseIdRoute: typeof DatabaseDatabaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database/$databaseId': {
      id: '/database/$databaseId'
      path: '/database/$databaseId'
      fullPath: '/database/$databaseId'
      preLoaderRoute: typeof DatabaseDatabaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatabaseDatabaseIdRoute: DatabaseDatabaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
