/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DatabaseDatabaseIdImport } from './routes/database.$databaseId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DatabaseDatabaseIdRoute = DatabaseDatabaseIdImport.update({
  id: '/database/$databaseId',
  path: '/database/$databaseId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/database/$databaseId': {
      id: '/database/$databaseId'
      path: '/database/$databaseId'
      fullPath: '/database/$databaseId'
      preLoaderRoute: typeof DatabaseDatabaseIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/database/$databaseId': typeof DatabaseDatabaseIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/database/$databaseId': typeof DatabaseDatabaseIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/database/$databaseId': typeof DatabaseDatabaseIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/database/$databaseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/database/$databaseId'
  id: '__root__' | '/' | '/database/$databaseId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatabaseDatabaseIdRoute: typeof DatabaseDatabaseIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatabaseDatabaseIdRoute: DatabaseDatabaseIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/database/$databaseId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/database/$databaseId": {
      "filePath": "database.$databaseId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
